AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for Roman Numerals Converter Application

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
         - t2.micro
         - t3.micro
         - t2.small
    Description: EC2 instance type for the application

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the key pair to associate with the EC2 instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bef6cc322bfff646
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroups:
        - !Ref SecurityGroup
      UserData: Base64: |
          #! /bin/bash
          yum update -y
          yum install python3
          pip3 install flask
          cd /home/ec2-user
          FOLDER="https://github.com/bekirbilgec/aws-project/blob/main/Project-001-Roman-Numerals-Converter/"
          wget ${FOLDER}/app.py
          mkdir templates && cd templates
          wget ${FOLDER}/templates/index.html
          wget ${FOLDER}/templates/result.html
          cd ..
          python3 app.py
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Description: The instance ID of the EC2 instance running the Roman Numerals Converter Application
  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: The public IP address of the EC2 instance

  
